name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven

    - name: Build with Maven
      # Apuntamos a la carpeta donde realmente está tu pom.xml
      run: mvn -B package --file vib_ED_pt2/pom.xml

    - name: Upload JAR artifact
      # ACTUALIZADO A V4: Esto soluciona tu error actual
      uses: actions/upload-artifact@v4
      with:
        name: vib_ED_tests-jar
        path: vib_ED_pt2/target/*.jar
